version: '3'

services:
  fileservice:
    image: file-service:0.2
    volumes:
      - /home/hiraishin/Documents/fileservice:/fileservice/filesave:rw
    env_file:
      - .env
    entrypoint:
      - ./uvc.sh
    depends_on:
      - database
    ports:
      - 8000:8000

  database:
    image: postgres:13
    volumes:
      - /var/lib/pgsql/data:/var/lib/postgresql/data:rw
      # - ./db:/docker-entrypoint-initdb.d:ro
    ports:
      - 5433:5432
    
